// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBttHAaELtnzpkwwm93471lG9P0kzNvW4A',
    appId: '1:887252136076:web:aa00eea13604a2ab06cba9',
    messagingSenderId: '887252136076',
    projectId: 'flutterfire-ui-codelab-2035f',
    authDomain: 'flutterfire-ui-codelab-2035f.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-2035f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9XnIwNpvpTlRSwc0zry7_QHzXufFBqU',
    appId: '1:887252136076:android:f14f95bf6bad7de306cba9',
    messagingSenderId: '887252136076',
    projectId: 'flutterfire-ui-codelab-2035f',
    storageBucket: 'flutterfire-ui-codelab-2035f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2T7DQN_HmL5MSRzSP7j-UzxrQyFGPd2c',
    appId: '1:887252136076:ios:de0527b5b24cc59c06cba9',
    messagingSenderId: '887252136076',
    projectId: 'flutterfire-ui-codelab-2035f',
    storageBucket: 'flutterfire-ui-codelab-2035f.appspot.com',
    iosClientId: '887252136076-2ekphd061gbneijaemt90ncehrs552md.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2T7DQN_HmL5MSRzSP7j-UzxrQyFGPd2c',
    appId: '1:887252136076:ios:de0527b5b24cc59c06cba9',
    messagingSenderId: '887252136076',
    projectId: 'flutterfire-ui-codelab-2035f',
    storageBucket: 'flutterfire-ui-codelab-2035f.appspot.com',
    iosClientId: '887252136076-2ekphd061gbneijaemt90ncehrs552md.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
